### ISSUE TITLE
Crash with tc3

### ISSUE THREAD

**Issue by wormzjl** [hypercross/hx#1]
服务器上如果一个人在另外一个人附近用TC3的挖矿法杖的话另外一个人会client crash

Stacktrace:
    at hx.Lockit.EventHandler.onClientBreakLocked(EventHandler.java:92)
    at net.minecraftforge.event.ASMEventHandler_121_EventHandler_onClientBreakLocked_BreakSpeed.invoke(.dynamic)
    at net.minecraftforge.event.ASMEventHandler.invoke(ASMEventHandler.java:35)
    at net.minecraftforge.event.EventBus.post(EventBus.java:103)
    at net.minecraftforge.event.ForgeEventFactory.getBreakSpeed(ForgeEventFactory.java:28)
    at qx.getCurrentPlayerStrVsBlock(EntityPlayer.java:847)
    at net.minecraftforge.common.ForgeHooks.blockStrength(ForgeHooks.java:150)
    at amq.a(Block.java:688)
    at thaumcraft.common.items.wands.ItemWandExcavation.onUsingItemTick(ItemWandExcavation.java:118)
    at qx.j_(EntityPlayer.java:275)
    at bah.j_(SourceFile:65)
    at yc.a(World.java:2291)
    at yc.g(World.java:2253)

**Comment by wormzjl** [comment]
完整的错误报告
http://pastebin.com/QjTsaa1W

**Comment by profjb** [comment]
I have a close error to this.
--- BEGIN ERROR REPORT 2c03c45c --------
Full report at:
C:\Users\Profjb\AppData\Roaming\FeedTheBeast\prot3ch\minecraft\crash-reports\crash-2013-02-17_22.24.35-client.txt
Please show that file to Mojang, NOT just this screen!

Generated 17/02/13 22:24

-- Head --
Stacktrace:
at hx.Lockit.EventHandler.onClientBreakLocked(EventHandler.java:92)
at net.minecraftforge.event.ASMEventHandler_119_EventHandler_onClientBreakLocked_BreakSpeed.invoke(.dynamic)
at net.minecraftforge.event.ASMEventHandler.invoke(ASMEventHandler.java:35)
at net.minecraftforge.event.EventBus.post(EventBus.java:103)
at net.minecraftforge.event.ForgeEventFactory.getBreakSpeed(ForgeEventFactory.java:28)
at net.minecraftforge.common.ForgeHooks.blockStrength(ForgeHooks.java:145)
at amq.a(Block.java:688)
at thaumcraft.common.items.wands.ItemWandExcavation.onUsingItemTick(ItemWandExcavation.java:118)
at qx.j_(EntityPlayer.java:275)
at bah.j_(SourceFile:65)
at yc.a(World.java:2291)
at yc.g(World.java:2253)

-- Entity being ticked --
Details:
Entity Type: null (com.thevoxelbox.voxelplayer.VoxelPlayerEntityOtherPlayerMP)
Entity ID: 1528
Name: yellownarwhalrus
Exact location: -3520.95, 66.00, 1661.01
Block location: World: (-3521,66,1661), Chunk: (at 15,4,13 in -221,103; contains blocks -3536,0,1648 to -3521,255,1663), Region: (-7,3; contains chunks -224,96 to -193,127, blocks -3584,0,1536 to -3073,255,2047)
Momentum: 0.00, 0.00, 0.00
Stacktrace:
at yc.h(World.java:2107)

-- Affected level --
Details:
Level name: MpServer
All players: 2 total; [ays['profjb'/13444, l='MpServer', x=-3570.00, y=68.62, z=1705.20], VoxelPlayerEntityOtherPlayerMP['yellownarwhalrus'/1528, l='MpServer', x=-3520.95, y=66.00, z=1661.01]]
Chunk stats: MultiplayerChunkCache: 441
Level seed: 0
Level generator: ID 00 - default, ver 1. Features enabled: false
Level generator options: 
Level spawn location: World: (-3570,67,1705), Chunk: (at 14,4,9 in -224,106; contains blocks -3584,0,1696 to -3569,255,1711), Region: (-7,3; contains chunks -224,96 to -193,127, blocks -3584,0,1536 to -3073,255,2047)
Level time: 6371139 game time, 7827940 day time
Level dimension: 0
Level storage version: 0x00000 - Unknown?
Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Forced entities: 117 total; [qn['Skeleton'/32521, l='MpServer', x=-3530.50, y=44.00, z=1701.02], oy['Chicken'/1, l='MpServer', x=-3526.56, y=34.00, z=1678.63], oy['Chicken'/3, l='MpServer', x=-3525.41, y=47.00, z=1679.41], qr['Zombie'/34131, l='MpServer', x=-3576.50, y=14.00, z=1663.50], mc['entity.ItemFrame.name'/4, l='MpServer', x=-3530.50, y=86.50, z=1669.06], mc['entity.ItemFrame.name'/5, l='MpServer', x=-3529.50, y=86.50, z=1669.06], mc['entity.ItemFrame.name'/6, l='MpServer', x=-3532.50, y=101.50, z=1675.06], oy['Chicken'/29380, l='MpServer', x=-3507.68, y=58.34, z=1658.78], oy['Chicken'/29381, l='MpServer', x=-3508.42, y=59.24, z=1655.68], qr['Zombie'/31573, l='MpServer', x=-3602.50, y=20.00, z=1729.50], qr['Zombie'/34426, l='MpServer', x=-3580.50, y=33.00, z=1751.50], qc['Creeper'/19799, l='MpServer', x=-3574.50, y=54.00, z=1679.50], qc['Creeper'/32552, l='MpServer', x=-3564.50, y=22.00, z=1752.50], px['item.item.feather'/34169, l='MpServer', x=-3532.16, y=5.13, z=1659.81], px['item.item.chickenCooked'/34170, l='MpServer', x=-3532.78, y=5.13, z=1660.66], px['item.item.chickenRaw'/32826, l='MpServer', x=-3511.14, y=59.13, z=1656.98], px['item.item.feather'/32825, l='MpServer', x=-3506.67, y=57.13, z=1659.20], qn['Skeleton'/32831, l='MpServer', x=-3570.50, y=33.00, z=1748.50], qr['Zombie'/30082, l='MpServer', x=-3600.97, y=24.00, z=1728.47], MLEntityGenericMale@7208216: Erwin Lothar/2891603243816400982/ayp@40e8688d, qd['Enderman'/34393, l='MpServer', x=-3532.50, y=49.00, z=1646.50], qn['Skeleton'/34157, l='MpServer', x=-3621.50, y=45.00, z=1693.50], EntityAtmosMoth['Moth'/33913, l='MpServer', x=-3609.92, y=12.77, z=1722.05], oy['Chicken'/33299, l='MpServer', x=-3510.50, y=65.00, z=1657.66], VoxelPlayerEntityOtherPlayerMP['yellownarwhalrus'/1528, l='MpServer', x=-3520.31, y=66.00, z=1662.47], px['item.item.egg'/33389, l='MpServer', x=-3522.85, y=22.13, z=1683.13], ow['Bat'/31022, l='MpServer', x=-3579.53, y=36.10, z=1745.06], qr['Zombie'/26073, l='MpServer', x=-3563.91, y=50.00, z=1727.47], qr['Zombie'/33652, l='MpServer', x=-3547.50, y=23.00, z=1632.50], px['item.item.egg'/32852, l='MpServer', x=-3509.82, y=7.13, z=1666.13], px['item.item.feather'/29569, l='MpServer', x=-3520.13, y=47.13, z=1670.38], px['item.item.chickenRaw'/29570, l='MpServer', x=-3517.28, y=5.13, z=1666.91], oy['Chicken'/28533, l='MpServer', x=-3511.95, y=55.00, z=1669.73], oy['Chicken'/29572, l='MpServer', x=-3512.22, y=66.00, z=1659.53], oy['Chicken'/29335, l='MpServer', x=-3512.78, y=66.00, z=1659.68], EntityAtmosMcFish['Minecraft Fish'/28256, l='MpServer', x=-3601.57, y=61.88, z=1718.30], pd['Pig'/25511, l='MpServer', x=-3517.32, y=55.00, z=1668.44], oy['Chicken'/29948, l='MpServer', x=-3516.69, y=60.37, z=1667.97], MLEntityGenericMale@8894020: Alwine Didrik/636528554346086926/ayp@40e8688d, ow['Bat'/33823, l='MpServer', x=-3604.50, y=41.93, z=1701.31], oy['Chicken'/29333, l='MpServer', x=-3512.78, y=66.00, z=1657.38], oy['Chicken'/29950, l='MpServer', x=-3512.75, y=66.00, z=1658.19], EntityAtmosReefManta['Reef Manta'/28255, l='MpServer', x=-3601.57, y=62.00, z=1718.30], qr['Zombie'/33354, l='MpServer', x=-3608.50, y=12.00, z=1724.50], qp['Spider'/27402, l='MpServer', x=-3535.13, y=19.00, z=1653.72], px['item.item.egg'/24354, l='MpServer', x=-3526.13, y=33.13, z=1679.13], VoxelPlayerEntityOtherPlayerMP['yellownarwhalrus'/1528, l='MpServer', x=-3517.94, y=66.00, z=1658.59], qr['Zombie'/34314, l='MpServer', x=-3569.50, y=22.00, z=1755.50], MLEntityGenericMale@1694575: Gisela Didrik/473695386872799074/ayp@40e8688d, qn['Skeleton'/31266, l='MpServer', x=-3626.50, y=22.00, z=1722.50], qn['Skeleton'/31269, l='MpServer', x=-3610.50, y=20.00, z=1745.50], qc['Creeper'/34086, l='MpServer', x=-3580.50, y=15.00, z=1684.50], qn['Skeleton'/31270, l='MpServer', x=-3595.50, y=20.00, z=1762.88], qn['Skeleton'/33125, l='MpServer', x=-3570.58, y=35.00, z=1753.59], MLEntityGenericMale@8012935: Alwine Manfred/3879805624708476024/ayp@40e8688d, oy['Chicken'/19371, l='MpServer', x=-3510.69, y=58.00, z=1669.53], oy['Chicken'/19370, l='MpServer', x=-3504.56, y=62.48, z=1641.56], oy['Chicken'/19373, l='MpServer', x=-3509.53, y=7.00, z=1667.47], oy['Chicken'/19375, l='MpServer', x=-3517.44, y=5.00, z=1665.56], qc['Creeper'/33988, l='MpServer', x=-3593.50, y=6.00, z=1670.50], oy['Chicken'/19363, l='MpServer', x=-3504.16, y=56.00, z=1661.97], qc['Creeper'/24280, l='MpServer', x=-3566.00, y=48.00, z=1680.47], oy['Chicken'/19364, l='MpServer', x=-3498.41, y=62.50, z=1639.59], oy['Chicken'/19367, l='MpServer', x=-3517.13, y=66.00, z=1664.28], oy['Chicken'/19384, l='MpServer', x=-3510.44, y=56.00, z=1670.81], oy['Chicken'/19385, l='MpServer', x=-3510.59, y=56.00, z=1670.19], oy['Chicken'/19386, l='MpServer', x=-3517.47, y=4.43, z=1670.36], oy['Chicken'/19387, l='MpServer', x=-3524.69, y=22.00, z=1683.53], EntityBrainyZombie['Angry Zombie'/32661, l='MpServer', x=-3516.50, y=11.00, z=1656.50], oy['Chicken'/19388, l='MpServer', x=-3525.28, y=22.00, z=1683.47], VoxelPlayerEntityOtherPlayerMP['yellownarwhalrus'/1528, l='MpServer', x=-3519.00, y=66.00, z=1661.16], oy['Chicken'/696, l='MpServer', x=-3525.85, y=22.00, z=1683.53], qr['Zombie'/32662, l='MpServer', x=-3627.50, y=47.00, z=1706.50], oy['Chicken'/19376, l='MpServer', x=-3518.75, y=36.00, z=1664.47], oy['Chicken'/19377, l='MpServer', x=-3510.41, y=39.00, z=1666.53], pd['Pig'/19379, l='MpServer', x=-3519.31, y=48.00, z=1670.50], oy['Chicken'/19380, l='MpServer', x=-3530.56, y=6.00, z=1655.47], oy['Chicken'/19382, l='MpServer', x=-3539.38, y=6.00, z=1665.59], oy['Chicken'/19383, l='MpServer', x=-3517.85, y=5.00, z=1669.83], qn['Skeleton'/31481, l='MpServer', x=-3574.31, y=33.00, z=1726.22], qo['Slime'/27119, l='MpServer', x=-3575.69, y=14.00, z=1679.69], EntityAtmosStarFish['Starfish'/19343, l='MpServer', x=-3607.50, y=47.00, z=1668.50], mg['Painting'/19342, l='MpServer', x=-3548.00, y=97.00, z=1687.06], mg['Painting'/19341, l='MpServer', x=-3547.94, y=95.00, z=1690.50], VoxelPlayerEntityOtherPlayerMP['yellownarwhalrus'/1528, l='MpServer', x=-3520.95, y=66.00, z=1661.01], qc['Creeper'/28073, l='MpServer', x=-3604.50, y=40.00, z=1739.50], VoxelPlayerEntityOtherPlayerMP['yellownarwhalrus'/1528, l='MpServer', x=-3520.95, y=66.00, z=1661.01], oy['Chicken'/19355, l='MpServer', x=-3516.53, y=45.00, z=1657.66], oy['Chicken'/19359, l='MpServer', x=-3496.41, y=53.00, z=1669.53], oy['Chicken'/19356, l='MpServer', x=-3516.56, y=45.00, z=1659.59], qn['Skeleton'/32952, l='MpServer', x=-3616.50, y=22.00, z=1710.50], oy['Chicken'/19345, l='MpServer', x=-3538.22, y=62.52, z=1659.79], MLEntityGenericMale@4710134: Ludvig de Conteville/4050197257795030878/ayp@40e8688d, pd['Pig'/24208, l='MpServer', x=-3520.10, y=64.00, z=1635.17], oy['Chicken'/29458, l='MpServer', x=-3514.16, y=66.69, z=1663.75], oy['Chicken'/29459, l='MpServer', x=-3517.94, y=66.00, z=1664.78], qn['Skeleton'/34474, l='MpServer', x=-3606.50, y=37.00, z=1700.50], qr['Zombie'/34473, l='MpServer', x=-3545.50, y=16.00, z=1647.50], px['item.item.egg'/34193, l='MpServer', x=-3518.88, y=5.13, z=1662.13], qn['Skeleton'/32712, l='MpServer', x=-3573.50, y=27.00, z=1754.50], pd['Pig'/33222, l='MpServer', x=-3520.21, y=66.00, z=1648.53], qc['Creeper'/33219, l='MpServer', x=-3570.41, y=33.00, z=1754.44], qr['Zombie'/33769, l='MpServer', x=-3616.50, y=22.00, z=1707.50], px['item.item.egg'/30293, l='MpServer', x=-3524.13, y=47.13, z=1679.18], qr['Zombie'/30881, l='MpServer', x=-3618.50, y=22.00, z=1732.50], pd['Pig'/24206, l='MpServer', x=-3522.83, y=63.00, z=1664.49], ays['profjb'/13444, l='MpServer', x=-3570.00, y=68.62, z=1705.20], pd['Pig'/26186, l='MpServer', x=-3509.55, y=63.00, z=1653.45], qc['Creeper'/33955, l='MpServer', x=-3506.00, y=47.00, z=1666.41], oy['Chicken'/34432, l='MpServer', x=-3517.03, y=66.00, z=1658.75], oy['Chicken'/27040, l='MpServer', x=-3512.78, y=66.00, z=1658.75], oy['Chicken'/32486, l='MpServer', x=-3514.69, y=66.00, z=1658.31], pd['Pig'/27272, l='MpServer', x=-3535.73, y=64.00, z=1636.47], mg['Painting'/19342, l='MpServer', x=-3548.00, y=97.00, z=1687.06], mg['Painting'/19341, l='MpServer', x=-3547.94, y=95.00, z=1690.50], qn['Skeleton'/34455, l='MpServer', x=-3586.50, y=17.00, z=1671.50], MLEntityGenericMale@6979111: Richard Didrik/3131911752936719753/ayp@40e8688d]
Retry entities: 0 total; []
Stacktrace:
at ayp.a(WorldClient.java:440)
at net.minecraft.client.Minecraft.b(Minecraft.java:2401)
at net.minecraft.client.Minecraft.run(Minecraft.java:787)
at java.lang.Thread.run(Unknown Source)

-- System Details --
Details:
Minecraft Version: 1.4.7
Operating System: Windows 7 (amd64) version 6.1
Java Version: 1.7.0_06, Oracle Corporation
Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
Memory: 383082728 bytes (365 MB) / 1203347456 bytes (1147 MB) up to 3723231232 bytes (3550 MB)
LiteLoader Mods: 3 loaded mod(s)
- VoxelPacket version 2.0.1
- VoxelPlayer version 0.9.3
- VoxelMenu version 1.4.6
  JVM Flags: 5 total; -Xms256M -Xmx3584M -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:+AggressiveOpts
  AABB Pool Size: 2721 (152376 bytes; 0 MB) allocated, 989 (55384 bytes; 0 MB) used
  Suspicious classes: FML and Forge are installed
  IntCache: cache: 0, tcache: 0, allocated: 3, tallocated: 63
  FML: 
  mcp Minecraft Coder Pack Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
  FML Forge Mod Loader Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
  Forge Minecraft Forge Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
  mod_CodeChickenCore CodeChicken Core Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
  Lockit Lockit Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
  NotEnoughItems Not Enough Items Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
  denLib denLib Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
  mod_Lockit Lockit Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
  BuildCraft|Core BuildCraft Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
  BuildCraft|Energy BC Energy Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
  ExtrabiomesXL ExtrabiomesXL Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
  Forestry Forestry for Minecraft Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
  ComputerCraft ComputerCraft Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
  CCTurtle ComputerCraft Turtles Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
  ThermalExpansion Thermal Expansion Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
  OmniTools OmniTools Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
  IC2 IndustrialCraft 2 Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
  TC Traincraft Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
  drceph.petrogen Petroleum Generator Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
  AdvancedMachines IC2 Advanced Machines Addon.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
  AdvancedSolarPanel Advanced Solar Panels Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
  AtmosMobs Atmosmobs mod Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
  BuildCraft|Builders BC Builders Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
  BuildCraft|Factory BC Factory Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
  BuildCraft|Transport BC Transport Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
  BuildCraft|Silicon BC Silicon Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
  Additional-Buildcraft-Objects Additional Buildcraft Objects Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
  ChargePads Charge Pads.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
  ChickenChunks ChickenChunks Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
  Chocolatecraft Chocolatecraft Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
  EE3 Equivalent Exchange 3 Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
  EnderStorage EnderStorage.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
  BinnieCore Binnie Core Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
  ExtraBees Extra Bees Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
  factorization Factorization Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
  GraviSuite Gravitation Suite Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
  Railcraft Railcraft Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
  RedPowerCore RedPower Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
  RedPowerBase RP Base Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
  RedPowerMachine RP Machine Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
  RedPowerCompat RP Compat Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
  RedPowerWiring RP Wiring Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
  RedPowerLogic RP Logic Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
  RedPowerLighting RP Lighting Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
  RedPowerWorld RP World Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
  RedPowerControl RP Control Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
  ThermalExpansion|Factory Factory Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
  ThermalExpansion|Energy Energy Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
  ThermalExpansion|Transport Transport Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
  TwilightForest The Twilight Forest Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
  GregTech_Addon GregTech-Addon Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
  IC2NuclearControl Nuclear Control Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
  mod_InvTweaks Inventory Tweaks Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
  IronChest Iron Chest Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
  Millenaire Millénaire Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
  minechem MineChem Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
  AS_Minions Minions Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
  MiscPeripherals MiscPeripherals Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
  ModularForceFieldSystem Modular ForceField System V2 Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
  Mystcraft Mystcraft Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
  NEIPlugins NEI Plugins Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
  Thaumcraft Thaumcraft Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
  OCS OpenCCSensors Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
  PetBat Pet Bat.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
  PowerCrystalsCore PowerCrystals Core Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
  PowerConverters Power Converters Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
  RecipeRemover Recipe Remover (1).zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
  mod_ReiMinimap mod_ReiMinimap Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
  SoulShards SoulShards Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
  StevesCarts Steve's Carts Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
  ThermalExpansion|NEI NEI Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
  TrailMix TrailMix Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
  WR-CBE|Core WR-CBE Core Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
  WR-CBE|Addons WR-CBE Addons Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
  WR-CBE|RedPower WR-CBE RedPower Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
  LWJGL: 2.4.2
  OpenGL: Intel(R) HD Graphics Family GL version 3.1.0 - Build 8.15.10.2372, Intel
  Is Modded: Definitely; Client brand changed to 'forge,fml'
  Type: Client (map_client.txt)
  Texture Pack: Default
  Profiler Position: N/A (disabled)
  Vec3 Pool Size: 2335 (130760 bytes; 0 MB) allocated, 258 (14448 bytes; 0 MB) used

java.lang.ClassCastException: com.thevoxelbox.voxelplayer.VoxelPlayerEntityOtherPlayerMP cannot be cast to ays
at hx.Lockit.EventHandler.onClientBreakLocked(EventHandler.java:92)
at net.minecraftforge.event.ASMEventHandler_119_EventHandler_onClientBreakLocked_BreakSpeed.invoke(.dynamic)
at net.minecraftforge.event.ASMEventHandler.invoke(ASMEventHandler.java:35)
at net.minecraftforge.event.EventBus.post(EventBus.java:103)
at net.minecraftforge.event.ForgeEventFactory.getBreakSpeed(ForgeEventFactory.java:28)
at net.minecraftforge.common.ForgeHooks.blockStrength(ForgeHooks.java:145)
at amq.a(Block.java:688)
at thaumcraft.common.items.wands.ItemWandExcavation.onUsingItemTick(ItemWandExcavation.java:118)
at qx.j_(EntityPlayer.java:275)
at bah.j_(SourceFile:65)
at yc.a(World.java:2291)
at yc.g(World.java:2253)
at yc.h(World.java:2107)
at net.minecraft.client.Minecraft.l(Minecraft.java:1863)
at net.minecraft.client.Minecraft.J(Minecraft.java:846)
at net.minecraft.client.Minecraft.run(Minecraft.java:771)
at java.lang.Thread.run(Unknown Source)
--- END ERROR REPORT c95024cb ----------

**Comment by hypercross** [comment]
obsolete
